---
- hosts: all
  remote_user: duncansungwkim
  become: yes
  tasks:
  - name: stop the Docker daemon
    ignore_errors: yes
    service: name=docker state=stopped
  - name: ensure that APT works with the https method
    apt: name=apt-transport-https state=present force=yes update_cache=yes
  - name: install CA certificates
    apt: name=ca-certificates state=present force=yes
  - name: add the new pgp key for Docker
    apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
  - name: delete the existing apt source of Docker
    file: path=/etc/apt/sources.list.d/docker.list state=absent
  - name: add the apt source for Docker
    apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-trusty main" state=present update_cache=yes
  - name: purge the old repo
    apt: name=lxc-docker* purge=yes state=absent
    ignore_errors: yes
  - name: verify that apt is pulling from the right repository
    command: apt-cache policy docker-engine
  - name: install the linux-image-extra kernel package for Docker
    apt: name=linux-image-extra-{{ ansible_kernel }} state=present force=yes update_cache=yes
  - name: install Docker
    apt: name=docker-engine state=present force=yes update_cache=yes
  - name: start the Docker daemon
    service: name=docker state=started
  - name: install PIP for Docker Compose
    apt: name=python-pip state=present force=yes
  - name: install Docker Compose
    pip: name=docker-compose
  - name: register variable for installing Docker Compose command completion
    shell: docker-compose --version | awk 'NR==1{print $NF}'
    register: docker_compose_build
    ignore_errors: True
  - name: install Docker Compose command completion
    get_url: url=https://raw.githubusercontent.com/docker/compose/{{ docker_compose_build.stdout }}/contrib/completion/bash/docker-compose dest=/etc/bash_completion.d/docker-compose
